# Generated by Django 4.1.3 on 2022-12-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.PositiveIntegerField()),
                ('hobby', models.CharField(blank=True, max_length=255)),
                ('marital_status', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
